### PR TITLE
Fix non-BitmapDrawable support, add animated GIF to sample app

### PR DESCRIPTION
**Pull request by edenman**

### CODE REVIEW

**Comment by edenman** [comment]
@igreenwood what do you think?

**Comment by igreenwood** [comment]
@edenman 
Sorry for late response.
Thank you for your pr 🙌 
 I have tried your pr in my device. Your idea is really nice, but I want to center the image. Do you have any idea for fixing this issue?

**Comment by igreenwood** [comment]
Hmm...I have found one more problem. Zooming is collapsing 😅

**Comment by edenman** [comment]
Ah, that's because I was sticking with the existing convention of having the sample depend on an existing version of the library. Just pushed a commit that depends on the local modules which shows the centering and zoom behavior working correctly.

There's an issue with animated GIFs when you have the shared element transition turned on, but I'm not using that feature so I haven't investigated it yet (and don't really plan to, to be honest)

**Comment by igreenwood** [comment]
Oh...that was a slip up. Sorry!
The new version works perfect 👍

**Pull request merged**
